name: 'Vitest Coverage Report'
description: 'Provide a Vitest Test Coverage Report as Step-Summary and comment in Pull Requests'
author: 'David Losert'
inputs:
  github-token:
      required: false
      description: 'A github access token. Uses secrets.GITHUB_TOKEN by default.'
      default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
