name: 'Vitest Coverage Report'
description: 'Provide a Vitest Test Coverage Report as Step-Summary and comment in Pull Requests'
author: 'David Losert'
inputs:
  github-token:
      required: false
      description: 'A github access token with permissions to write to issues. Uses secrets.GITHUB_TOKEN by default.'
      default: ${{ github.token }}
  vite-config-path:
      required: false
      description: 'The path to the vite config file. Uses "vite.config.js" by default.'
      default: vite.config.js
  json-summary-path:
      required: false
      description: 'The path to the json summary file. Uses "coverage/coverage-summary.json" by default.'
      default: coverage/coverage-summary.json
  json-final-path:
      required: false
      description: 'The path to the json final file. Uses "coverage/coverage-final.json" by default.'
      default: coverage/coverage-final.json
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'green'
